require 'friendly_id'
require 'acts_as_list'
require 'awesome_nested_set'
require 'awesome_nested_set-tools'
require 'route_translator'
require 'icalendar'
require 'haml-rails'
require 'ecm_calendar_helper'

require 'ecm/courses'
require 'ecm/courses/engine'
